services:
  - type: web
    name: discordbot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TOKEN
        sync: false
